package dev.kevindubois.demo;

import io.quarkus.runtime.Startup;
import io.quarkus.scheduler.Scheduled;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import org.eclipse.microprofile.config.inject.ConfigProperty;
import org.jboss.logging.Logger;

import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.atomic.AtomicLong;

/**
 * Built-in load generator that continuously generates traffic to the application's own endpoints.
 * This enables fast and accurate analysis during canary deployments by ensuring consistent traffic.
 * 
 * The load generator:
 * - Starts automatically when the application starts (after a configurable delay)
 * - Generates configurable requests per second (default: 50 req/sec)
 * - Hits the /api/status endpoint
 * - Runs asynchronously without blocking the main application
 * - Can be disabled via configuration for local development
 */
@Startup
@ApplicationScoped
public class LoadGeneratorService {
    
    private static final Logger LOG = Logger.getLogger(LoadGeneratorService.class);
    
    @Inject
    MetricsResource metricsResource;
    
    @Inject
    UserResource userResource;
    
    @ConfigProperty(name = "load.generator.enabled", defaultValue = "true")
    boolean enabled;
    
    @ConfigProperty(name = "load.generator.requests.per.second", defaultValue = "50")
    int requestsPerSecond;
    
    @ConfigProperty(name = "load.generator.startup.delay", defaultValue = "5s")
    String startupDelay;
    
    private final ExecutorService executorService = Executors.newFixedThreadPool(10);
    private final AtomicLong totalGeneratedRequests = new AtomicLong(0);
    private volatile boolean initialized = false;
    
    /**
     * Scheduled method that generates load at the configured rate.
     * Runs every second and generates the configured number of requests per second.
     * Quarkus scheduler doesn't support intervals less than 1 second, so we batch the requests.
     */
    @Scheduled(every = "1s", delay = 5, delayUnit = java.util.concurrent.TimeUnit.SECONDS)
    void generateLoad() {
        if (!enabled) {
            return;
        }
        
        // Check if resources are initialized before proceeding
        if (metricsResource == null || userResource == null) {
        }
            return;
            LOG.warn("Resources not yet initialized, skipping load generation cycle");
        if (metricsResource == null || userResource == null) {
            LOG.warn("Resources not yet initialized, skipping load generation cycle");
            return;
        }
        
        // Log initialization message once
        if (!initialized) {
            initialized = true;
            LOG.info("Load generator started - generating " + requestsPerSecond + " requests/second");
            LOG.info("Load generator will hit /api/status (80%) and /api/user (20%) endpoints");
        }
        
        // Generate the configured number of requests per second
        for (int i = 0; i < requestsPerSecond; i++) {
            // Generate request asynchronously to avoid blocking the scheduler
            CompletableFuture.runAsync(() -> {
                try {
                    // 20% of requests hit the user endpoint, 80% hit status endpoint
                    if (Math.random() < 0.2) {
                        // Call user endpoint with random user ID (1-10)
                        int userId = (int) (Math.random() * 10) + 1;
                        userResource.getUser(String.valueOf(userId));
                    } else {
                        // Call the status endpoint
                        metricsResource.getStatus();
                    }
                    
                    long count = totalGeneratedRequests.incrementAndGet();
                    
                    // Log progress every 100 requests
                    if (count % 100 == 0) {
                        LOG.debug("Load generator: " + count + " requests generated");
                    }
                    
                    // Log milestone every 1000 requests
                    if (count % 1000 == 0) {
                        LOG.info("Load generator milestone: " + count + " total requests generated");
                    }
                    
                } catch (Exception e) {
                    // Catch and log exceptions without failing the app
                    LOG.error("Load generator request failed: " + e.getMessage());
                    // Don't rethrow - we want the load generator to continue
                }
            }, executorService);
        }
    }
    
    /**
     * Get the total number of requests generated by the load generator.
     * Useful for monitoring and debugging.
     */
    public long getTotalGeneratedRequests() {
        return totalGeneratedRequests.get();
    }
    
    /**
     * Check if the load generator is enabled.
     */
    public boolean isEnabled() {
        return enabled;
    }
    
    /**
     * Get the configured requests per second rate.
     */
    public int getRequestsPerSecond() {
        return requestsPerSecond;
    }
}

